platform :ios, '14.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(
    File.join('..', 'Flutter', 'Generated.xcconfig'),
    __FILE__
  )

  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist."
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end

  raise "FLUTTER_ROOT not found"
end

require File.expand_path(
  File.join('packages', 'flutter_tools', 'bin', 'podhelper'),
  flutter_root
)

flutter_ios_podfile_setup

target 'Runner' do

  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods(
    File.dirname(File.realpath(__FILE__))
  )

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|

  installer.pods_project.targets.each do |target|

    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|

      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'

      config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'

      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'

      config.build_settings['ENABLE_BITCODE'] = 'NO'

      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',

        'PERMISSION_CAMERA=1',
        'PERMISSION_PHOTOS=1',
        'PERMISSION_LOCATION=1',
        'PERMISSION_NOTIFICATIONS=1'
      ]
    end
  end
end

# platform :ios, '14.0'
#
# ENV['COCOAPODS_DISABLE_STATS'] = 'true'
#
# project 'Runner', {
#   'Debug' => :debug,
#   'Profile' => :release,
#   'Release' => :release,
# }
#
# def flutter_root
#   generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
#   unless File.exist?(generated_xcode_build_settings_path)
#     raise "#{generated_xcode_build_settings_path} must exist. Run flutter pub get first"
#   end
#
#   File.foreach(generated_xcode_build_settings_path) do |line|
#     matches = line.match(/FLUTTER_ROOT\=(.*)/)
#     return matches[1].strip if matches
#   end
#   raise "FLUTTER_ROOT not found"
# end
#
# require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)
#
# flutter_ios_podfile_setup
#
# target 'Runner' do
#   use_frameworks!
#   use_modular_headers!
#
#   flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
#
#   target 'RunnerTests' do
#     inherit! :search_paths
#   end
# end
#
# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     flutter_additional_ios_build_settings(target)
#
#     target.build_configurations.each do |config|
#       # ✅ Important fixes
#       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
#       config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
#       config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'
#       config.build_settings['ENABLE_BITCODE'] = 'NO'
#
#       # ✅ Permissions
#       config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
#         '$(inherited)',
#         'PERMISSION_CAMERA=1',
#         'PERMISSION_PHOTOS=1',
#         'PERMISSION_LOCATION=1',
#         'PERMISSION_NOTIFICATIONS=1'
#       ]
#     end
#   end
# end



# platform :ios, '14.0'
#
# ENV['COCOAPODS_DISABLE_STATS'] = 'true'
#
# project 'Runner', {
#   'Debug' => :debug,
#   'Profile' => :release,
#   'Release' => :release,
# }
#
# def flutter_root
#   generated_xcode_build_settings_path = File.expand_path(
#     File.join('..', 'Flutter', 'Generated.xcconfig'),
#     __FILE__
#   )
#
#   unless File.exist?(generated_xcode_build_settings_path)
#     raise "#{generated_xcode_build_settings_path} must exist. Run flutter pub get first"
#   end
#
#   File.foreach(generated_xcode_build_settings_path) do |line|
#     matches = line.match(/FLUTTER_ROOT\=(.*)/)
#     return matches[1].strip if matches
#   end
#
#   raise "FLUTTER_ROOT not found"
# end
#
# require File.expand_path(
#   File.join('packages', 'flutter_tools', 'bin', 'podhelper'),
#   flutter_root
# )
#
# flutter_ios_podfile_setup
#
# target 'Runner' do
#   use_frameworks!
#   use_modular_headers!
#
#   flutter_install_all_ios_pods(
#     File.dirname(File.realpath(__FILE__))
#   )
#
#   target 'RunnerTests' do
#     inherit! :search_paths
#   end
# end
#
# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#
#     flutter_additional_ios_build_settings(target)
#
#     target.build_configurations.each do |config|
#
#       # iOS Version
#       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
#
#       # Modern Xcode Fixes
#       config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
#       config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'NO'
#       config.build_settings['ENABLE_BITCODE'] = 'NO'
#
#       # Permissions
#       config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
#         '$(inherited)',
#
#         'PERMISSION_CAMERA=1',
#         'PERMISSION_PHOTOS=1',
#         'PERMISSION_LOCATION=1',
#         'PERMISSION_NOTIFICATIONS=1'
#       ]
#     end
#
#     # Firebase Header Auto Fix
#     if target.respond_to?(:source_build_phase)
#
#       target.source_build_phase.files.each do |file|
#
#         path = file.file_ref&.real_path
#
#         next unless path && File.exist?(path)
#
#         if File.extname(path) == '.h'
#
#           content = File.read(path)
#
#           if content.include?('#import <Firebase/Firebase.h>')
#
#             puts "Patching #{File.basename(path)}"
#
#             content.gsub!(
#               '#import <Firebase/Firebase.h>',
#               '#import <FirebaseCore/FirebaseCore.h>'
#             )
#
#             File.write(path, content)
#           end
#         end
#       end
#     end
#   end
# end





